apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kube-soomkiller
build:
  artifacts:
    - image: ttl.sh/kube-soomkiller
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: true
  tagPolicy:
    sha256: {}
manifests:
  kustomize:
    paths:
      - deploy
deploy:
  kubectl: {}
