apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kube-soomkiller
build:
  artifacts:
    - image: rophy/kube-soomkiller
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: true
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - deploy/*.yaml
deploy:
  kubectl: {}
