apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kube-soomkiller
build:
  artifacts:
    - image: rophy/kube-soomkiller
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VERSION: '{{cmd "git" "describe" "--tags" "--always" "--dirty"}}'
  local:
    push: true
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - deploy/soomkiller/*.yaml
deploy:
  kubectl: {}
profiles:
  - name: e2e
    manifests:
      rawYaml:
        - deploy/soomkiller/*.yaml
        - deploy/e2e/*.yaml
  - name: stress
    manifests:
      rawYaml:
        - deploy/soomkiller/*.yaml
        - deploy/stress/*.yaml
